
skip_tags: true

skip_branch_with_pr: true

image:
# - Visual Studio 2013
# - Visual Studio 2015
# - Visual Studio 2017
# - Visual Studio 2019
- Visual Studio 2022
# - Ubuntu # Ubuntu and Ubuntu1804 are the same
# - Ubuntu2004
# - Ubuntu1604
# - macOS
# - macOS-BigSur
# - macOS-Mojave

artifacts:
- path: .output\*.nupkg
  name: PowerShellGallery
- path: .output\*.zip
  name: GitHub
- path: .output\*.xml

build:
  verbosity: minimal

build_script:
- ps: .\build.ps1
