
skip_tags: true

skip_branch_with_pr: true

image:
# - Visual Studio 2013
# - Visual Studio 2015
# - Visual Studio 2017
# - Visual Studio 2019
- Visual Studio 2022
# - Ubuntu # Ubuntu and Ubuntu1804 are the same
# - Ubuntu2004
# - Ubuntu1604
# - macOS
# - macOS-BigSur
# - macOS-Mojave

artifacts:
- path: .output\*.nupkg
  name: NuGet
- path: .output\*.zip
  name: GitHub
- path: .output\*.xml

nuget:
  project_feed: true

build:
  verbosity: minimal

build_script:
- ps: .\build.ps1
# - pwsh: dir 'env:' ; .\build.ps1

# for:
# - matrix:
#     only:
#       - image: Visual Studio 2013
#       # These run PowerShell Core 6, which doesn't support COM.
#       - image: Visual Studio 2015
#       - image: Visual Studio 2017
#   build_script:
#   - ps: .\build.ps1

# - matrix:
#     only:
#     - image: Visual Studio 2022
#   environment:
#     PUBLISH: True
